name: Run tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installs Lein Dependencies
        uses: ./.github/actions/install-lein-deps
      - name: Install dependencies
        run: npm ci
      - name: Compiles app and test
        run: npx shadow-cljs compile app test
      - name: Runs tests on karma
        run: npx karma start --single-run

  Creates-App-Release-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installs Lein Dependencies
        uses: ./.github/actions/install-lein-deps
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Releases app
        run: npx shadow-cljs release app
